INSERT INTO video (titulo, url) VALUES ('Curso de Java 01: Introdução e Dicas para quem está Começando', 'LnORjqZUMIQ');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 02: Instalando o Java no Windows (Windows XP, Windows 7, Windows 8)', 'ddhH97IPrFY');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 02: Instalando o Java no Windows 10', 'CMHU5buXvNw');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 03: Instalando o Java no Ubuntu (Linux)', 'BTNp4P12DIs');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 04: Instalando o Java no Mac OS', 'xQEauKE4NTw');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 05: Primeiro Programa em Java', 'mu2ti43cgwc');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 05', '3rZNefsMmKs');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 06: Passando argumentos para o programa', 'dhGPGv7XCM8');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 06', 'Ebvl0BlnD-U');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 07: Entendendo os Erros', 'NoEoOaTSFMo');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 08: Instalando uma IDE (Eclipse e Netbeans) no Windows, Ubuntu e MacOS', '74QEhBpzixs');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 09: Introdução à Orientação a Objetos', 'KUUrrIX6wGo');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 10: Introdução a Variávels', 'ELBqT_rueAQ');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 11: Variáveis - Tipos Primitivos', 'aqiB58NpKLw');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 12: Lendo dados do teclado usando a classe Scanner', 'Z6Y8zupCKfk');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 13: Operadores (Aritiméticos, Lógicos e Relacionais)', '199tKAE6sxo');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 13', 'pfI20o_lyRA');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 14: Condicionais If-Else', 'KJYSXTYgL_o');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 15: Condicional Switch-Case', 'JTLgFZyBUN4');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 15 (if-else e switch-case)', '-BpAWP6T6a8');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 16: Loops while e do-while', '9_12LPVMJYc');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 17: Loop for', 'HrfWrbmFUKQ');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 17 (while, do-while, for) Parte 1', '7ccdc5Vkf7Q');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 17 (while, do-while, for) Parte 2', 'ATEpiDIqDx4');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 17 (while, do-while, for) Parte 3', 'ltG7MEnTx8M');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 17 (while, do-while, for) Parte 4', 'bfkocfgM7_U');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 17 (while, do-while, for) Parte 5', 'coiYSnquB7g');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 18: Comandos Break e Continue', 'rU-DCmwAtXE');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 19: Vetores (Arrays)', 'HxRb5KLofcI');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 19 Vetores (Arrays) - Parte 1', 'UN6ZJBSTR0M');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 19 Vetores (Arrays) - Parte 2', 'o4S35dlr4_E');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 19 Vetores (Arrays) - Parte 3', 'eAuxsgm3pl4');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 19 Vetores (Arrays) - Parte 4', 'NZw0BbGxCmM');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 19 Vetores (Arrays) - Parte 5', '64Bj0RMWkiU');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 20 Matrizes (Arrays Multidimensionais) - Parte 1', 'P66G0rxdL-k');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 20 Matrizes (Arrays Multidimensionais) - Parte 2', 'C6lhdwDo2Ng');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 20 Matrizes (Arrays Multidimensionais) - Parte 3', '99u1tAbYcww');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 20 Matrizes (Arrays Multidimensionais) - Parte 4', 'QjSlHLMaTYY');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 20 Matrizes (Arrays Multidimensionais) - Parte 1', 'Cf4sv_9vENs');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 20 Matrizes (Arrays Multidimensionais) - Parte 2', 'lHKmF-kOq90');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 20 Matrizes (Arrays Multidimensionais) - Parte 3', 'zaD6mQj11ew');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 20 Matrizes (Arrays Multidimensionais) - Parte 4', '9h9OfzW9u9M');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 21: Loop for each', '2ndBbnsqBXQ');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 22: Como debugar no Eclipse', 'kbzzlKfjR8k');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 23: Como debugar no Netbeans', 'qlMJytCpKJg');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 24 - Orientação a Objetos: Classes e atributos', 'Gq1BS63pkRA');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 24: Classes e atributos', '0f5wWNU_nns');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 25 - Orientação a Objetos: Classes e métodos simples', '-t_c6F_Uoeg');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 26 - Orientação a Objetos: Classes e métodos com retorno', '_3fal2H8Agw');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 27 - Orientação a Objetos: Classes e métodos com parâmetros', 'ffvsI9dnDiY');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 27: Classes e métodos - Parte 1', 'DTewirzLmb4');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 27: Classes e métodos - Parte 2', 'SC7YLvc6Sto');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 27: Classes e métodos - Parte 3', 'eYM24XWAxSs');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 27: Classes e métodos - Parte 4', 'ZILUIBmGAmk');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 28 - Orientação a Objetos: Pacotes e import', 'aRQHjfYBpM8');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 29 - Orientação a Objetos: Construtores', 'uJKcKzro9pU');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 30 - Orientação a Objetos: Palavra chave this', 'RLzR--Pwvcs');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 31 - Orientação a Objetos: Modificadores private e public', '6oD7TE90e-M');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 32 - Orientação a Objetos: Encapsulamento: métodos getters e setters', 'vKif9IxYTLY');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 33 - Orientação a Objetos: Sobrecarga de métodos e construtores (overload)', 'ZpssJov_5_A');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 33 - Parte 1', 'eFYqJHZw2G8');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 33 - Parte 2', 'LNTGVzYVtMk');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 33 - Parte 3', 'iGyM6wL_w50');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 33 - Parte 4', 'cv8-GNYNOOo');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 34 - Orientação a Objetos: Variáveis e metodos estáticos (modificador static)', 'Dz_w4YpFL80');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 34 - Parte 1 (Contador)', 'oTy5jP7CK9c');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 34 - Parte 2 (Calculadora)', '8GGSXaUj2pk');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 34 - Parte 3 (Fatorial)', 'A8caJRDWWVQ');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 35 - Recursividade', 'X56_FjmbmE4');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 35 - Parte 1 (Fibonacci Recursivo)', '2YyJ3CZBlAI');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 35 - Parte 2 (Somatório Recursivo)', 'wl1gIU5y-II');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 36 - Orientação a Objetos: Relacionamento entre Classes (tem um e tem muitos)', 'edXQiFAdH2c');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 36 - Parte 1 (Agenda)', '5-dQS7QuwcY');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 36 - Parte 2 (Curso + Alunos)', 'ML32UfX43Pw');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 37 - Orientação a Objetos: Herança', 'MOXLCjL4Ik4');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 38 - Orientação a Objetos: Herança: Palavra chave super', 'aRPal-8z4RQ');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 39 - Orientação a Objetos: Herança: modificadores de acesso + protected', 'xjxDh9xbfLM');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 40: Orientação a Objetos: Herança e Polimorfismo: sobrecarga de métodos', 'pMPlngyWHLM');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 41: Orientação a Objetos: Herança: classes abstratas', 'Oibb-17nD14');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 42: Orientação a Objetos: Palavra chave final', '858FJ6DQRVg');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 43: Orientação a Objetos: Classe Object', 'dAGvL88bO9o');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 43 - Parte 1 (Conta Bancária)', 'Ghp5pmbxDTU');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 43 - Parte 2 (Imposto de Renda)', 'ZSyCf11JJOM');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 43 - Parte 3 (Zoológico)', 'M631ZCkX-Dg');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 44: Orientação a Objetos: Interfaces', '6uLLfRNgRA4');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 45: Orientação a Objetos: Casting e instaceof', 'POEf8DKZWds');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 46: Orientação a Objetos: Interface e herança', 'h-R4mWzmRKc');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 46 - Parte 1 (Figura Geométrica)', '3hZCLp0g1TE');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 46 - Parte 2 (Dimensão e Volume)', '2M1qOF24HMA');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 46 - Parte 3 (Polimorfismo)', 'mLHT8GxG0Sw');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 47: Exceptions: try, catch', 'ld2C4GcAtsg');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 48: Exceptions: multiplos catch', 'G8-fhwpHdFU');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 49: Exceptions: finally', 'Xb9rK6L4GYA');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 50: Exceptions: stacktrace e throws', 'CW7DER5TqLM');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 51: Exceptions: tipos de erros no Java', '5R8pw1V2H-g');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 52: Exceptions: criando sua própria exceção', 'Xt0CpwJT5yY');
INSERT INTO video (titulo, url) VALUES ('Curso de Java: Correção Exercícios Aula 52: Exceptions', 'tc48uwR9Qto');
INSERT INTO video (titulo, url) VALUES ('Curso de Java: Como gerar o certificado', 'rTlaAFpbfMs');

