INSERT INTO video (titulo, url) VALUES ('Curso de Java 01: Introdução e Dicas para quem está Começando', 'https://www.youtube.com/embed/LnORjqZUMIQ');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 02: Instalando o Java no Windows (Windows XP, Windows 7, Windows 8)', 'https://www.youtube.com/embed/ddhH97IPrFY');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 02: Instalando o Java no Windows 10', 'https://www.youtube.com/embed/CMHU5buXvNw');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 03: Instalando o Java no Ubuntu (Linux)', 'https://www.youtube.com/embed/BTNp4P12DIs');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 04: Instalando o Java no Mac OS', 'https://www.youtube.com/embed/xQEauKE4NTw');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 05: Primeiro Programa em Java', 'https://www.youtube.com/embed/mu2ti43cgwc');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 05', 'https://www.youtube.com/embed/3rZNefsMmKs');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 06: Passando argumentos para o programa', 'https://www.youtube.com/embed/dhGPGv7XCM8');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 06', 'https://www.youtube.com/embed/Ebvl0BlnD-U');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 07: Entendendo os Erros', 'https://www.youtube.com/embed/NoEoOaTSFMo');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 08: Instalando uma IDE (Eclipse e Netbeans) no Windows, Ubuntu e MacOS', 'https://www.youtube.com/embed/74QEhBpzixs');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 09: Introdução à Orientação a Objetos', 'https://www.youtube.com/embed/KUUrrIX6wGo');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 10: Introdução a Variávels', 'https://www.youtube.com/embed/ELBqT_rueAQ');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 11: Variáveis - Tipos Primitivos', 'https://www.youtube.com/embed/aqiB58NpKLw');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 12: Lendo dados do teclado usando a classe Scanner', 'https://www.youtube.com/embed/Z6Y8zupCKfk');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 13: Operadores (Aritiméticos, Lógicos e Relacionais)', 'https://www.youtube.com/embed/199tKAE6sxo');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 13', 'https://www.youtube.com/embed/pfI20o_lyRA');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 14: Condicionais If-Else', 'https://www.youtube.com/embed/KJYSXTYgL_o');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 15: Condicional Switch-Case', 'https://www.youtube.com/embed/JTLgFZyBUN4');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 15 (if-else e switch-case)', 'https://www.youtube.com/embed/-BpAWP6T6a8');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 16: Loops while e do-while', 'https://www.youtube.com/embed/9_12LPVMJYc');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 17: Loop for', 'https://www.youtube.com/embed/HrfWrbmFUKQ');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 17 (while, do-while, for) Parte 1', 'https://www.youtube.com/embed/7ccdc5Vkf7Q');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 17 (while, do-while, for) Parte 2', 'https://www.youtube.com/embed/ATEpiDIqDx4');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 17 (while, do-while, for) Parte 3', 'https://www.youtube.com/embed/ltG7MEnTx8M');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 17 (while, do-while, for) Parte 4', 'https://www.youtube.com/embed/bfkocfgM7_U');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 17 (while, do-while, for) Parte 5', 'https://www.youtube.com/embed/coiYSnquB7g');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 18: Comandos Break e Continue', 'https://www.youtube.com/embed/rU-DCmwAtXE');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 19: Vetores (Arrays)', 'https://www.youtube.com/embed/HxRb5KLofcI');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 19 Vetores (Arrays) - Parte 1', 'https://www.youtube.com/embed/UN6ZJBSTR0M');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 19 Vetores (Arrays) - Parte 2', 'https://www.youtube.com/embed/o4S35dlr4_E');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 19 Vetores (Arrays) - Parte 3', 'https://www.youtube.com/embed/eAuxsgm3pl4');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 19 Vetores (Arrays) - Parte 4', 'https://www.youtube.com/embed/NZw0BbGxCmM');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 19 Vetores (Arrays) - Parte 5', 'https://www.youtube.com/embed/64Bj0RMWkiU');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 20 Matrizes (Arrays Multidimensionais) - Parte 1', 'https://www.youtube.com/embed/P66G0rxdL-k');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 20 Matrizes (Arrays Multidimensionais) - Parte 2', 'https://www.youtube.com/embed/C6lhdwDo2Ng');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 20 Matrizes (Arrays Multidimensionais) - Parte 3', 'https://www.youtube.com/embed/99u1tAbYcww');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 20 Matrizes (Arrays Multidimensionais) - Parte 4', 'https://www.youtube.com/embed/QjSlHLMaTYY');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 20 Matrizes (Arrays Multidimensionais) - Parte 1', 'https://www.youtube.com/embed/Cf4sv_9vENs');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 20 Matrizes (Arrays Multidimensionais) - Parte 2', 'https://www.youtube.com/embed/lHKmF-kOq90');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 20 Matrizes (Arrays Multidimensionais) - Parte 3', 'https://www.youtube.com/embed/zaD6mQj11ew');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 20 Matrizes (Arrays Multidimensionais) - Parte 4', 'https://www.youtube.com/embed/9h9OfzW9u9M');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 21: Loop for each', 'https://www.youtube.com/embed/2ndBbnsqBXQ');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 22: Como debugar no Eclipse', 'https://www.youtube.com/embed/kbzzlKfjR8k');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 23: Como debugar no Netbeans', 'https://www.youtube.com/embed/qlMJytCpKJg');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 24 - Orientação a Objetos: Classes e atributos', 'https://www.youtube.com/embed/Gq1BS63pkRA');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 24: Classes e atributos', 'https://www.youtube.com/embed/0f5wWNU_nns');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 25 - Orientação a Objetos: Classes e métodos simples', 'https://www.youtube.com/embed/-t_c6F_Uoeg');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 26 - Orientação a Objetos: Classes e métodos com retorno', 'https://www.youtube.com/embed/_3fal2H8Agw');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 27 - Orientação a Objetos: Classes e métodos com parâmetros', 'https://www.youtube.com/embed/ffvsI9dnDiY');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 27: Classes e métodos - Parte 1', 'https://www.youtube.com/embed/DTewirzLmb4');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 27: Classes e métodos - Parte 2', 'https://www.youtube.com/embed/SC7YLvc6Sto');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 27: Classes e métodos - Parte 3', 'https://www.youtube.com/embed/eYM24XWAxSs');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 27: Classes e métodos - Parte 4', 'https://www.youtube.com/embed/ZILUIBmGAmk');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 28 - Orientação a Objetos: Pacotes e import', 'https://www.youtube.com/embed/aRQHjfYBpM8');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 29 - Orientação a Objetos: Construtores', 'https://www.youtube.com/embed/uJKcKzro9pU');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 30 - Orientação a Objetos: Palavra chave this', 'https://www.youtube.com/embed/RLzR--Pwvcs');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 31 - Orientação a Objetos: Modificadores private e public', 'https://www.youtube.com/embed/6oD7TE90e-M');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 32 - Orientação a Objetos: Encapsulamento: métodos getters e setters', 'https://www.youtube.com/embed/vKif9IxYTLY');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 33 - Orientação a Objetos: Sobrecarga de métodos e construtores (overload)', 'https://www.youtube.com/embed/ZpssJov_5_A');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 33 - Parte 1', 'https://www.youtube.com/embed/eFYqJHZw2G8');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 33 - Parte 2', 'https://www.youtube.com/embed/LNTGVzYVtMk');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 33 - Parte 3', 'https://www.youtube.com/embed/iGyM6wL_w50');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 33 - Parte 4', 'https://www.youtube.com/embed/cv8-GNYNOOo');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 34 - Orientação a Objetos: Variáveis e metodos estáticos (modificador static)', 'https://www.youtube.com/embed/Dz_w4YpFL80');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 34 - Parte 1 (Contador)', 'https://www.youtube.com/embed/oTy5jP7CK9c');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 34 - Parte 2 (Calculadora)', 'https://www.youtube.com/embed/8GGSXaUj2pk');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 34 - Parte 3 (Fatorial)', 'https://www.youtube.com/embed/A8caJRDWWVQ');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 35 - Recursividade', 'https://www.youtube.com/embed/X56_FjmbmE4');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 35 - Parte 1 (Fibonacci Recursivo)', 'https://www.youtube.com/embed/2YyJ3CZBlAI');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Correção Exercícios Aula 35 - Parte 2 (Somatório Recursivo)', 'https://www.youtube.com/embed/wl1gIU5y-II');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 36 - Orientação a Objetos: Relacionamento entre Classes (tem um e tem muitos)', 'https://www.youtube.com/embed/edXQiFAdH2c');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 36 - Parte 1 (Agenda)', 'https://www.youtube.com/embed/5-dQS7QuwcY');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 36 - Parte 2 (Curso + Alunos)', 'https://www.youtube.com/embed/ML32UfX43Pw');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 37 - Orientação a Objetos: Herança', 'https://www.youtube.com/embed/MOXLCjL4Ik4');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 38 - Orientação a Objetos: Herança: Palavra chave super', 'https://www.youtube.com/embed/aRPal-8z4RQ');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 39 - Orientação a Objetos: Herança: modificadores de acesso + protected', 'https://www.youtube.com/embed/xjxDh9xbfLM');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 40: Orientação a Objetos: Herança e Polimorfismo: sobrecarga de métodos', 'https://www.youtube.com/embed/pMPlngyWHLM');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 41: Orientação a Objetos: Herança: classes abstratas', 'https://www.youtube.com/embed/Oibb-17nD14');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 42: Orientação a Objetos: Palavra chave final', 'https://www.youtube.com/embed/858FJ6DQRVg');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 43: Orientação a Objetos: Classe Object', 'https://www.youtube.com/embed/dAGvL88bO9o');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 43 - Parte 1 (Conta Bancária)', 'https://www.youtube.com/embed/Ghp5pmbxDTU');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 43 - Parte 2 (Imposto de Renda)', 'https://www.youtube.com/embed/ZSyCf11JJOM');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 43 - Parte 3 (Zoológico)', 'https://www.youtube.com/embed/M631ZCkX-Dg');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 44: Orientação a Objetos: Interfaces', 'https://www.youtube.com/embed/6uLLfRNgRA4');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 45: Orientação a Objetos: Casting e instaceof', 'https://www.youtube.com/embed/POEf8DKZWds');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 46: Orientação a Objetos: Interface e herança', 'https://www.youtube.com/embed/h-R4mWzmRKc');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 46 - Parte 1 (Figura Geométrica)', 'https://www.youtube.com/embed/3hZCLp0g1TE');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 46 - Parte 2 (Dimensão e Volume)', 'https://www.youtube.com/embed/2M1qOF24HMA');
INSERT INTO video (titulo, url) VALUES ('Curso de Java - Orientação a Objetos: Correção Exercícios Aula 46 - Parte 3 (Polimorfismo)', 'https://www.youtube.com/embed/mLHT8GxG0Sw');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 47: Exceptions: try, catch', 'https://www.youtube.com/embed/ld2C4GcAtsg');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 48: Exceptions: multiplos catch', 'https://www.youtube.com/embed/G8-fhwpHdFU');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 49: Exceptions: finally', 'https://www.youtube.com/embed/Xb9rK6L4GYA');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 50: Exceptions: stacktrace e throws', 'https://www.youtube.com/embed/CW7DER5TqLM');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 51: Exceptions: tipos de erros no Java', 'https://www.youtube.com/embed/5R8pw1V2H-g');
INSERT INTO video (titulo, url) VALUES ('Curso de Java 52: Exceptions: criando sua própria exceção', 'https://www.youtube.com/embed/Xt0CpwJT5yY');
INSERT INTO video (titulo, url) VALUES ('Curso de Java: Correção Exercícios Aula 52: Exceptions', 'https://www.youtube.com/embed/tc48uwR9Qto');
INSERT INTO video (titulo, url) VALUES ('Curso de Java: Como gerar o certificado', 'https://www.youtube.com/embed/rTlaAFpbfMs');

